### ISSUE TITLE
Feature request: Configure notifications

### ISSUE THREAD

**Issue by ddeimeke** [jasoncheng/dica#107]
It would be great to configure notifications from inside the app.

Select Sound, Vibrations, general notifications.

**Comment by jasoncheng** [comment]
@ddeimeke I just notice that in android application settings , already can config notification for DiCa
(ex. sound / vibrations / and even override no Do Not Disturb) ; and also in system notification bar, you can quick launch setting to system config page ( i never use that before, it's already functional and convenient ).

and also, from the past few days that i research on notification configure, config those setting on different android platform will spent a lot of time on development; and it require more device for testing to make sure it work (especially on android 8/9, new notification channel setting)

May i know why config notification inside DiCa is important to you ? is there something default system can not do ?

![001](https://user-images.githubusercontent.com/540463/50383836-6784f900-06f6-11e9-9e60-63b93846d9a3.jpg)
![002](https://user-images.githubusercontent.com/540463/50383837-6784f900-06f6-11e9-893a-c0bce076e4d4.jpg)

**Comment by ddeimeke** [comment]
It is mainly due to consistency. Nearly every Android application allows the configuration of notifcations from inside the app.

But, you are right with more recent Android versions you can configure it in the Android settings.

**Comment by jasoncheng** [comment]
Roger that. Thanks for explanation and understand;
Please allow me set it to close or treat it as low priority;
I'll develop more functions to exchange notification configure, forgive me.

**Comment by jasoncheng** [comment]
@ddeimeke 👍
