### ISSUE TITLE
App chrashes on retweet

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#136]
Retweet is send but after that the app closes

**Comment by jasoncheng** [comment]
Newest version, I already hot fix , not work?!

**Comment by jasoncheng** [comment]
ok, will check later

**Comment by copiis** [comment]
hmm. a secon retweet succeedet

**Comment by jasoncheng** [comment]
i cannot reproduce yet, but i'll catch exception first

**Comment by copiis** [comment]
Sine today morning once it newer happened again

**Comment by jasoncheng** [comment]
okay, i'll retweet a lot, for find this issue
