### ISSUE TITLE
[feature request] Share from albut to DiCa

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#43]
It would be nice if it would be possible to share pictures and maybe videos directly from an Android album via the Share button to DiCa.
So after taking a photo with the camera app, send this photo to DiCa and create a new post.

**Comment by jasoncheng** [comment]
share is done, and i also implement for support video upload, but fail on video update;
no idea if that is API issue or mine, will open another issue for testing upload video, later.

**Comment by copiis** [comment]
I think we both do not mean the same thing. I once made a recording to clarify what I mean.
In other apps, there is the "Share" button and if I select this, I have DiCa not in the list to select.
https://meld.de/display/00d81f2c-115b-fa50-bfd9-30d386985488

**Comment by jasoncheng** [comment]
no like this?

![13771](https://user-images.githubusercontent.com/540463/48976876-c5a7c780-f0c9-11e8-9a2d-43195873bfad.jpg)
![13772](https://user-images.githubusercontent.com/540463/48976877-c5a7c780-f0c9-11e8-8ae5-f4691cf1e45a.jpg)

**Comment by copiis** [comment]
No, i dont't have DiCa in the List. Im on Android 9

**Comment by jasoncheng** [comment]
wow, it's need to implement, otherwise won't show; 
i will build a new beta version, then this new version will show on list :)
