### ISSUE TITLE
[feature request] Read without interruption

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#44]
Would it be possible that you continue reading where you left off, although the timeline has loaded more posts? So when starting the app, the timeline should be updated but the screen should stay in the same place and not jump to the last post.

**Comment by jasoncheng** [comment]
@copiis great idea; should be accomplish at this week, require some time on implement this

**Comment by jasoncheng** [comment]
not easy to implement this function, for each Item with dynamic layout and also different height, even move the cursor to last seen item, it still change position, is a challenge, lol.....temporary not merge into develop branch, until it work perfect

**Comment by copiis** [comment]
look great for me, i will test
