### ISSUE TITLE
Pictures are cropped despite OK

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#82]
Images should be cropped if you click on "crop", not on "OK".

**Comment by jasoncheng** [comment]
Status update: 
open a issue for this 
https://github.com/ArthurHub/Android-Image-Cropper/issues/634

**Comment by jasoncheng** [comment]
oh, wait.....i am so stupid, if i keep previous bitmap, then click on Ok; 
use previous bitmap, would solve this problem

**Comment by jasoncheng** [comment]
@copiis Sir, issue fixed :)
