### ISSUE TITLE
[feature request] Notifications in Android

### ISSUE THREAD

**Issue by copiis** [jasoncheng/dica#84]
It would be nice if there was a notification in Android for comments on their own posts or posts where you have commented yourself.

**Comment by jasoncheng** [comment]
i desire this function for a long time, currently, only two way can did this:

- a background service, keep polling notification API (but waste phone power)
- implement on this app only, which means real push notification, but **just only between who install DiCa**. and i also need to use Google Firebase Server as push notification service.

both, all not good solution

**Comment by jasoncheng** [comment]
@copiis what you think? Should i implement one of them?

**Comment by copiis** [comment]
I would suggest the first option with a query interval of 15 minutes.
I do not quite understand the second one. It should be valid anyway only for DiCa. What do you not like about the two solutions?

**Comment by jasoncheng** [comment]
status update:
find API issue , even i have seen, API still response (seen = 0), website already seen.
<img width="1202" alt="2018-12-14 1 47 17" src="https://user-images.githubusercontent.com/540463/49985484-0ac36900-ffa7-11e8-96aa-6349aa769aed.png">

**Comment by jasoncheng** [comment]
status update: almost ready, final testing
