### ISSUE TITLE
Alternative Download Source

### ISSUE THREAD

**Issue by IzzySoft** [jasoncheng/dica#98]
Currently, your app is only available in the walled garden of Playstore – and thus unreachable for folks without access to that. Would you consider offering an alternative download source – e.g. by attaching the APK to its corresponding release tag here at Github? Thanks in advance!

**Comment by jasoncheng** [comment]
@IzzySoft no problem sir, would also upload to F-Droid, many thanks for let me know about this

**Comment by IzzySoft** [comment]
F-Droid builds from your sources (so no APK upload). Taking your previous comment as you're supporting inclusion with F-Droid, I've opened an [Request for Packaging](https://gitlab.com/fdroid/rfp/issues/824) there. For that to proceed, you'd also need to specify a license for your project. I'm not sure whether F-Droid auto-update-checker can deal with the format of your tag names (`v<versionName>-<versionCode>` – we normally use `v<versionName>` or just `<versionName>`), but that we can figure then.

Thanks a lot first for agreeing at all! :wink:

**Comment by jasoncheng** [comment]
@IzzySoft 

This is my first time create  open source project, i really no idea what should i do; i learn to know [ what is F-Droid ] also today.

- What license should i specify, i really don't know, sorry about this, please let me know what should i do, i'll follow.
- I'll change tag name as you suggestion (<versionName>, ex. 0.1.4) for later release
- Should i delete those tags w/ bad format first?
- Thanks for opened an Request for Packaging
- If we use F-Droid, still need upload APK to GITHUB ?

yeah, learn a lot today :)

**Comment by jasoncheng** [comment]
hi teacher @IzzySoft , lol...cool 👍 
It's late in Taiwan, will read full article you post when i wake up .
Hit the sack. do action tomorrow

**Comment by jasoncheng** [comment]
@IzzySoft license updated, thanks again :)

**Comment by IzzySoft** [comment]
Cool, thanks! With F-Droid inclusion we've got an issue: GMS (Google Mobile Services) are a show-stopper (no proprietary components or other blobs allowed). May I suggest you attach an APK for now so I can include your app with my repo meanwhile?

As for GMS: You seem to use that for location services. Is that really essential for the app? Or maybe you could establish a build flavor that comes without that (unless you can do without that altogether)? That would make it possible to include the app with F-Droid then. GMS is the only "scanner error" we got on your repo.

**Comment by jasoncheng** [comment]
- APK file will update here: https://github.com/jasoncheng/dica/tree/apk/apk
- LocationService is for user to tag GeoLocation on post status
- who to build flavor, i have to study, no idea how to do this

**Comment by IzzySoft** [comment]
* app will be here: http://apt.izzysoft.de/fdroid/index/apk/cool.mixi.dica
* yes, I thought so – but is that essential? In the long run, you might find a substitute (there must be other libraries for that, or how does e.g. OsmAnd do that?)
* I'm no Android dev, so unfortunately I cannot help you with that. If you ask over in the RFP I've linked above, a dev will certainly give you at least a pointer. Done that for you, so with some luck one of the three I've pinged will show up here soon.

Thanks again!

**Comment by jasoncheng** [comment]
you're  welcome, you help me a lot on DiCa project, 
about the rest part, i'll do some research, when i find solution, will tag you, my teacher,
thanks for your work  :)

**Comment by IzzySoft** [comment]
Yes, please do. Also be welcome to chime in to the RFP directly.

**Comment by jasoncheng** [comment]
thank you teacher @IzzySoft

**Comment by IzzySoft** [comment]
@jasoncheng any news on the [build flavor](https://stackoverflow.com/questions/16737006/)? Did you find [some tutorial](https://www.androidauthority.com/building-multiple-flavors-android-app-706436/) and got started?

**Comment by IzzySoft** [comment]
@jasoncheng are you still on it – or did the project die? Last commit is more than 2 years ago now :(
